Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -29,3 +29,53 @@ jobs:
       
     - name: Build
       run: go build -v ./...
+
+    - name: Run application
+      run: go run main.go
+
+    - name: Test login endpoint
+      run: |
+        response=$(curl -X POST http://localhost:8080/login \
+          -H "Content-Type: application/json" \
+          -d '{"username": "testuser", "password": "testpassword"}')
+        echo $response
+        export ACCESS_TOKEN=$(echo $response | jq -r '.access_token')
+        export REFRESH_TOKEN=$(echo $response | jq -r '.refresh_token')  # Added extraction of refresh_token
+        echo "Access Token: $ACCESS_TOKEN"
+        echo "Refresh Token: $REFRESH_TOKEN"
+
+    - name: Test profile endpoint
+      run: |
+        if [ -z "$ACCESS_TOKEN" ]; then
+          echo "Access token is empty. Login failed."
+          exit 1
+        fi
+        profile_response=$(curl -X GET http://localhost:8080/auth/profile \
+          -H "Authorization: Bearer $ACCESS_TOKEN")
+        echo $profile_response
+
+    - name: Test refresh token endpoint
+      run: |
+        if [ -z "$REFRESH_TOKEN" ]; then
+          echo "Refresh token is empty. Login failed."
+          exit 1
+        fi
+        refresh_response=$(curl -X POST http://localhost:8080/refresh-token \
+          -H "Content-Type: application/json" \
+          -d '{"refresh_token": "'$REFRESH_TOKEN'"}')
+        echo $refresh_response
+        export NEW_ACCESS_TOKEN=$(echo $refresh_response | jq -r '.access_token')
+        echo "New Access Token: $NEW_ACCESS_TOKEN"
+
+    - name: Re-Test profile endpoint with new access token
+      run: |
+        if [ -z "$NEW_ACCESS_TOKEN" ]; then
+          echo "New Access token is empty. Refresh failed."
+          exit 1
+        fi
+        profile_response=$(curl -X GET http://localhost:8080/auth/profile \
+          -H "Authorization: Bearer $NEW_ACCESS_TOKEN")
+        echo $profile_response
+
+    - name: Test
+      run: go test -v ./...
